services:
   mysql:
      image: mysql:8.0
      container_name: mysql_container
      environment:
         MYSQL_ROOT_PASSWORD: root
      ports:
         - "3306:3306"
      volumes:
         - mysql_data:/var/lib/mysql
         - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
   mysql_data:
      driver: local