server:
   port: 8090
spring:
   application:
      name: product
   datasource:
      driver-class-name: org.postgresql.Driver
      username: root
      password: root
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=products
   jpa:
      properties:
         hibernate:
            default_schema: products
            dialect: org.hibernate.dialect.PostgreSQLDialect
            hbm2ddl:
               auto: create
            proc.param_null_passing: true
            jdbc:
               time_zone: UTC-3
            show-sql: true
   liquibase:
      change-log: liquibase/changelog.sql

springdoc:
   packagesToScan: com.naysinger.product.api
   writer-with-order-by-keys: true
   swagger-ui:
      path: /docs/swagger-ui.html