server:
   port: 8091
spring:
   application:
      name: order
   datasource:
      url: jdbc:mysql://localhost:3306/order_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      properties:
         hibernate:
            format_sql: false
            dialect: org.hibernate.dialect.MySQL8Dialect
            ddl-auto: none
            proc.param_null_passing: true
            jdbc:
               time_zone: UTC-3
            show-sql: true
   liquibase:
      change-log: liquibase/changelog.sql

springdoc:
   packagesToScan: com.naysinger.order.api
   writer-with-order-by-keys: true
   swagger-ui:
      path: /docs/swagger-ui.html
VALID_API_KEY: T35T3AP106D34
API_KEY_HEADER: ORDER-KEY