apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
   name: cosmos-backend
   description: IEL Cosmos - Backend
   annotations:
      backstage.io/techdocs-ref: dir:.
      "backstage.io/kubernetes-id": cosmos-backend
      "backstage.io/kubernetes-label-selector": "app=cosmos-backend"
      "jenkins.io/job-full-name": COSMOS/services
      sonarqube.org/project-key: br.org.fiergs:cosmos-backend
      grafana/tag-selector: "cosmos-backend"
   tags:
      - java
spec:
   type: service
   lifecycle: production
   owner: architecture
   system: fiergs-services-system
   providesApis:
      - cosmos-backend

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
   name: cosmos-backend
   description: IEL Cosmos - API
spec:
   type: openapi
   lifecycle: production
   owner: architecture
   system: fiergs-services-system
   definition:
      $text: http://10.100.250.178:31617/docs/v2/api-docs?group=v1
