version: "3.7"

services:
   mysql:
      image: mysql:8.0.15
      container_name: mysql_container
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: product
         MYSQL_USER: product
         MYSQL_PASSWORD: prod123
      ports:
         - "3306:3306"
      volumes:
         - mysql_data:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password

volumes:
   mysql_data:
      driver: local
